version: "3.8" 

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-arun}"
    image: cybulde-data
    container_name: cybulde-data-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-arunkumar}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-arunkumar}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME:-arunkumar}/.ssh
    ports:
      - 8888:8888
    ipc: host
    init: true